spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskFlowManager
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none

services:
  external:
    personal-number-api:
      url: http://localhost:8081/api/v1/personal_number